services:
  #travelAgency.userService.webapi:
  #  image: shop-backend-api:latest
  #  build:
  #    context: .
  #    dockerfile: Shop.WebApi/Dockerfile
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - USER_SECRETS_ID=77fae489-2981-4c9b-98fd-269c51a25c6b
  #  ports: 
  #    - "8083:80"
  #  volumes:
  #    - $APPDATA/Microsoft/UserSecrets/77fae489-2981-4c9b-98fd-269c51a25c6b:/root/.microsoft/usersecrets/77fae489-2981-4c9b-98fd-269c51a25c6b

  mssql:
    container_name: travelAgency.userService.sqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "ergo.1234"
    ports:
        - 1433:1433
    volumes:
        - sqlserver_data_container:/var/opt/mssql

volumes:
   sqlserver_data_container:
